// <auto-generated />
using System;
using GestionSpa.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionSpa.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626211416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionSpa.Api.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtendidoPor")
                        .HasColumnType("text");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("CuotaMensualId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int?>("SocioId")
                        .HasColumnType("integer");

                    b.Property<bool>("SumarACuota")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CuotaMensualId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("SocioId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.CuotaMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoCuota")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("MontoServicios")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId", "Mes", "Anio")
                        .IsUnique();

                    b.ToTable("CuotasMensuales");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccesoPermitido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CuotaMensualId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("RegistradoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("CuotaMensualId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("SoloSocios")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<decimal>("CuotaMensual")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Departamento")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedioPago")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("NumeroSocio")
                        .IsUnique();

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Cargo", b =>
                {
                    b.HasOne("GestionSpa.Api.Models.Cliente", "Cliente")
                        .WithMany("Cargos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionSpa.Api.Models.CuotaMensual", "CuotaMensual")
                        .WithMany("Cargos")
                        .HasForeignKey("CuotaMensualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionSpa.Api.Models.Servicio", "Servicio")
                        .WithMany("Cargos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSpa.Api.Models.Socio", "Socio")
                        .WithMany("Cargos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("CuotaMensual");

                    b.Navigation("Servicio");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.CuotaMensual", b =>
                {
                    b.HasOne("GestionSpa.Api.Models.Socio", "Socio")
                        .WithMany("Cuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Ingreso", b =>
                {
                    b.HasOne("GestionSpa.Api.Models.Socio", "Socio")
                        .WithMany("Ingresos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Pago", b =>
                {
                    b.HasOne("GestionSpa.Api.Models.Cargo", "Cargo")
                        .WithMany("Pagos")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionSpa.Api.Models.CuotaMensual", "CuotaMensual")
                        .WithMany("Pagos")
                        .HasForeignKey("CuotaMensualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cargo");

                    b.Navigation("CuotaMensual");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Cargo", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Cliente", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.CuotaMensual", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Servicio", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("GestionSpa.Api.Models.Socio", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Cuotas");

                    b.Navigation("Ingresos");
                });
#pragma warning restore 612, 618
        }
    }
}
